name: weather_by_me
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  geolocator: ^8.2.1
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Spartan MB
      fonts:
        - asset: assets/fonts/SpartanMB-Black.otf
          weight: 900